version: "1.0"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - proposta-network
  proposta-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proposta-app
    depends_on:
      - proposta-db
      - rabbitmq
    networks:
      - proposta-network
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - DB_HOST=proposta-db
      - DB_PORT=5432
      - DB_NAME=proposta-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - 8080:8080
  proposta-web:
    image: matheuspieropan/proposta-web
    container_name: proposta-web
    depends_on:
      - proposta-service
    ports:
      - "80:80"
    networks:
      - proposta-network
  proposta-db:
    container_name: proposta-db
    image: postgres:latest
    environment:
      POSTGRES_DB: proposta-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - proposta-network
    ports:
      - "5433:5432"
networks:
  proposta-network:
    driver: bridge
