version: "1.0"

services:
  proposta-service:
    build: .
    container_name: proposta-app
    depends_on:
      - propostadb
    networks:
      - proposta-network
    environment:
      - DB_HOST=payment-db
      - DB_PORT=5432
      - DB_NAME=payment-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - 8081:8081
  propostadb:
    container_name: proposta-db
    image: postgres:latest
    environment:
      POSTGRES_DB: proposta_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - proposta-network
    ports:
      - "5434:5432"

networks:
  proposta-network:
    driver: bridge