server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:propostadb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


# Springdoc OpenApi 3.1 & Swagger 3
springdoc:
  packagesToScan: com.pieropan.propostaapp.controller
  swagger-ui:
    path: /docs-propostaapp.html
  api-docs:
    path: /docs-propostaapp